### ISSUE TITLE
🍰  Feature Sliced Review

### ISSUE THREAD

**Issue by azinit** [tednaaa/react-starter-template#12]
**Во-первых, спасибо большое что решился заняться этим! 🚀 🚀** 

Отпишу основные мысли тут, остальное потом подробнее разберем)

---

P.S. 
- [Ссыль на воркспейс с кодом для ревью](https://github.dev/tednaaa/fsrt)

**Comment by azinit** [comment]
[`praise:`](https://conventionalcomments.org/#labels) Оч классно, что для начала решил ограничиться именно тремя слоями - т.к. это минимально необходимый базис как раз

![image](https://user-images.githubusercontent.com/42924400/144709811-28c39506-4edf-4973-8e5e-727e2f9fa2ce.png)

**Comment by azinit** [comment]
[`nitpick(critical):`](https://conventionalcomments.org/#labels) Но не очень, что для хуков отдельный сегмент выделяем

Лучше бы унифицировать и отдельную либо оформить, иначе свалка хелперов)

https://sova.dev/ru/why-utils-and-helpers-is-a-dump/

![image](https://user-images.githubusercontent.com/42924400/144709948-6fad602c-7a0f-407e-9b79-9fd2ed07a2fe.png)

**Comment by azinit** [comment]
Тут пока основное, потом как сделаем отдельный темплейт - там подробнее посмотрим)

Но как идея - оч круто!

> Есть мелкие замечания, но глянем это непосредственно в том же CRA-template

**Comment by tednaaa** [comment]
спасибо за ревью) будем дальше работать над cli =)
